### ISSUE TITLE
return instead of Promise.resolve

### ISSUE THREAD

**Issue by ORESoftware** [paulmillr/micro-should#1]
on my phone so cant submit a pr, but on line 9 of index.js you can prob just use `return` instead of `return Promise.resolve()`

**Comment by ORESoftware** [comment]
yw? idk I'm human i like when my contributions are acknowledged

**Comment by paulmillr** [comment]
Thank you, of course, but I like when people submit pull requests. It's pretty simple even from a phone.

**Comment by ORESoftware** [comment]
i know bro but a thank you is one line also, use your human brain
